wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: epoch_step
      6:
      - 3
    python_version: 3.9.7
    start_time: 1642452045
    t:
      1:
      - 1
      3:
      - 16
      4: 3.9.7
      5: 0.12.9
      8:
      - 5
adjoint:
  desc: null
  value: false
cpus:
  desc: null
  value: 1
early_stopping:
  desc: null
  value: 200
earlystopxT:
  desc: null
  value: 3
epoch:
  desc: null
  value: 10
gpus:
  desc: null
  value: 0
max_nfe:
  desc: null
  value: 5000
name:
  desc: null
  value: null
no_early:
  desc: null
  value: false
runs:
  desc: null
  value:
  - jm4q8qfz
seed:
  desc: null
  value: 43
sheaf_decay:
  desc: null
  value: null
sweep:
  desc: null
  value: 30j6cdj0
wandb_entity:
  desc: null
  value: bchamberlain
wandb_group:
  desc: null
  value: null
wandb_project:
  desc: null
  value: research-repo-sheaf_exp
